In [1]:
import sqlite3
import pandas as pd
con = sqlite3.connect(r"C:\\Users\Lenovo\Desktop\PROJECT\nfl.db")
df = pd.read_sql_query("SELECT season,avg(home_score) as home_score,avg(away_score) as away_score,avg(temp) as temp,avg(humidity) as humidity FROM 'game_info'  group by season", con)
df.to_csv('game_info.csv')
df

    season  home_score  away_score       temp   humidity
0     2002   23.018727   20.640449  60.955056  58.047393
1     2003   22.677903   19.112360  60.565543  59.822115
2     2004   22.906367   20.239700  59.902622  57.918660
3     2005   22.314607   18.786517  62.082397  53.738318
4     2006   21.258427   20.254682  61.071161  54.025000
5     2007   23.157303   20.228464  61.483146  58.472637
6     2008   23.183521   20.842697  61.157303  59.905000
7     2009   22.779026   20.382022  60.262172  59.454545
8     2010   23.000000   21.318352  59.314607  50.281250
9     2011   23.981273   20.509363  61.734082  48.157068
10    2012   24.119850   21.655431  61.213483  57.429319
11    2013   24.891386   21.977528  61.071161  58.561856
12    2014   23.973783   21.295880  61.172285  53.115000
13    2015   23.479401   21.985019  61.561798  56.580000
14    2016   24.363296   21.374532  61.958801  56.744186
15    2017   23.104869   20.524345  61.494382        NaN
16    2018   24.382022   22.168539  61.689139        NaN

In [2]:
df1 = pd.read_sql_query("SELECT * FROM 'team_roster' where season >= 2002 order by season", con)
df1.to_csv('team_roster.csv')
df1

,season,team,player_id,player_name,position,uniform_number,games_played,games_started,pfr_approx_value,experience,age,birth_date,height,weight,college,draft_info,salary
0,2002,atl,AmbrAs00,Ashley Ambrose,RCB,33.0,16.0,16.0,7.0,10.0,32.0,9/17/1970,5-11,190.0,missvalleyst,Indianapolis Colts / 2nd / 29th pick / 1992,NaN
1,2002,atl,BiblMa20,Martin Bibla,LG,64.0,10.0,0.0,1.0,Rook,23.0,10/4/1979,6-3,306.0,miami(fl),Atlanta Falcons / 4th / 116th pick / 2002,NaN
2,2002,atl,BoldJu20,Juran Bolden,LCB,21.0,14.0,6.0,4.0,6.0,28.0,6/27/1974,6-2,207.0,mississippideltacc,Atlanta Falcons / 4th / 127th pick / 1996,NaN
3,2002,atl,BrooKe00,Keith Brooking,LB,56.0,16.0,16.0,14.0,4.0,27.0,10/30/1975,6-2,245.0,georgiatech,Atlanta Falcons / 1st / 12th pick / 1998,NaN
4,2002,atl,BuchRa00,Ray Buchanan,LCB,34.0,12.0,11.0,5.0,9.0,31.0,9/29/1971,5-9,186.0,louisville,Indianapolis Colts / 3rd / 65th pick / 1993,NaN
5,2002,atl,CarpKe20,Keion Carpenter,FS,29.0,16.0,16.0,8.0,3.0,25.0,10/31/1977,5-11,205.0,virginiatech,None,NaN
6,2002,atl,CartJo22,Johndale Carty,LB,35.0,16.0,1.0,2.0,3.0,25.0,8/27/1977,6-0,196.0,utahst,Atlanta Falcons / 4th / 126th pick / 1999,NaN
7,2002,atl,ChiaDa00,Darrin Chiaverini,WR,82.0,7.0,0.0,0.0,3.0,25.0,10/12/1977,6-2,210.0,colorado,Cleveland Browns / 5th / 148th pick / 1999,NaN
8,2002,atl,ChriBo00,Bob Christian,FB,44.0,15.0,10.0,3.0,10.0,34.0,11/14/1968,5-11,226.0,northwestern,Atlanta Falcons / 12th / 310th pick / 1991,NaN
9,2002,atl,ClarTr20,Travis Claridge,LG,71.0,16.0,16.0,9.0,2.0,24.0,3/23/1978,6-5,300.0,usc,Atlanta Falcons / 2nd / 37th pick / 2000,NaN
10,2002,atl,CrumAl00,Alge Crumpler,TE,83.0,16.0,9.0,5.0,1.0,25.0,12/23/1977,6-2,262.0,nocarolina,Atlanta Falcons / 2nd / 35th pick / 2001,NaN
11,2002,atl,DrafCh20,Chris Draft,LB,54.0,15.0,5.0,5.0,4.0,26.0,2/26/1976,5-11,232.0,stanford,Chicago Bears / 6th / 157th pick / 1998,NaN
12,2002,atl,DuckT.00,T.J. Duckett,FB,45.0,12.0,3.0,4.0,Rook,21.0,2/17/1981,6-0,254.0,michiganst,Atlanta Falcons / 1st / 18th pick / 2002,NaN
13,2002,atl,DunnWa00,Warrick Dunn,RB,28.0,15.0,14.0,10.0,5.0,27.0,1/5/1975,5-9,180.0,floridast,Tampa Bay Buccaneers / 1st / 12th pick / 1997,NaN
14,2002,atl,feelyjay01,Jay Feely,K,4.0,16.0,0.0,4.0,1.0,26.0,5/23/1976,5-10,206.0,michigan,None,NaN
15,2002,atl,FinnBr00,Brian Finneran,WR,86.0,16.0,16.0,9.0,3.0,26.0,1/31/1976,6-5,210.0,villanova,None,NaN
16,2002,atl,FlemRo20,Ronald Flemons,DE,77.0,4.0,0.0,0.0,1.0,23.0,10/20/1979,6-5,265.0,texasam,Atlanta Falcons / 7th / 226th pick / 2001,NaN
17,2002,atl,FornKy20,Kynan Forney,RG,65.0,14.0,12.0,7.0,1.0,24.0,9/8/1978,6-3,307.0,hawaii,Atlanta Falcons / 7th / 219th pick / 2001,NaN
18,2002,atl,GarzRo20,Roberto Garza,RG,63.0,6.0,4.0,2.0,1.0,23.0,3/26/1979,6-2,296.0,texasamkingsville,Atlanta Falcons / 4th / 99th pick / 2001,NaN
19,2002,atl,GaylTr00,Trevor Gaylor,WR,81.0,13.0,2.0,4.0,2.0,25.0,11/3/1977,6-3,195.0,miami(oh),San Diego Chargers / 4th / 111th pick / 2000,NaN
20,2002,atl,GibsDa00,Damon Gibson,WR,87.0,1.0,0.0,0.0,4.0,27.0,2/25/1975,5-9,180.0,iowa,None,NaN
21,2002,atl,HallTr20,Travis Hall,DE,98.0,11.0,1.0,2.0,7.0,30.0,8/3/1972,6-5,295.0,byu,Atlanta Falcons / 6th / 181st pick / 1995,NaN
22,2002,atl,HeatRo20,Rodney Heath,LCB,25.0,1.0,0.0,0.0,3.0,28.0,10/29/1974,5-10,175.0,minnesota,None,NaN
23,2002,atl,HillKa20,Kahlil Hill,WR,87.0,1.0,0.0,0.0,Rook,23.0,3/18/1979,6-2,200.0,iowa,Atlanta Falcons / 6th / 184th pick / 2002,NaN
24,2002,atl,HoleJo20,John Holecek,LB,59.0,12.0,11.0,5.0,7.0,30.0,5/7/1972,6-2,240.0,illinois,Buffalo Bills / 5th / 144th pick / 1995,NaN
25,2002,atl,JackWi00,Willie Jackson,WR,80.0,7.0,1.0,2.0,7.0,31.0,8/16/1971,6-1,212.0,florida,Dallas Cowboys / 4th / 109th pick / 1994,NaN
26,2002,atl,JaspEd20,Ed Jasper,NT,95.0,16.0,16.0,7.0,5.0,29.0,1/18/1973,6-2,293.0,texasam,Philadelphia Eagles / 6th / 198th pick / 1997,NaN
27,2002,atl,JeffSh00,Shawn Jefferson,WR,84.0,13.0,7.0,4.0,11.0,33.0,2/22/1969,5-11,185.0,centralflorida,Houston Oilers / 9th / 240th pick / 1991,NaN
28,2002,atl,JervTr00,Travis Jervey,RB,36.0,6.0,0.0,0.0,7.0,30.0,5/5/1972,6-0,222.0,thecitadel,Green Bay Packers / 5th / 170th pick / 1995,NaN
29,2002,atl,JohnDo00,Doug Johnson,QB,11.0,6.0,1.0,2.0,2.0,25.0,10/27/1977,6-2,225.0,florida,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33706,2018,was,MoreFa00,Fabian Moreau,CB,31.0,16.0,10.0,4.0,1.0,24.0,4/9/1994,6-0,200.0,ucla,Washington Redskins / 3rd / 81st pick /2017,588000.0
33707,2018,was,MoseMo00,Morgan Moses,T,76.0,16.0,16.0,8.0,4.0,27.0,3/3/1991,6-6,335.0,virginia,Washington Redskins / 3rd / 66th pick /2014,3250000.0
33708,2018,was,NichMo00,Montae Nicholson,SS,35.0,14.0,7.0,3.0,1.0,23.0,12/4/1995,6-2,215.0,michiganst,Washington Redskins / 4th / 123rd pick /2017,555000.0
33709,2018,was,NormJo01,Josh Norman,CB,24.0,16.0,16.0,7.0,6.0,31.0,12/15/1987,6-0,200.0,coastalcarolina,Carolina Panthers / 5th / 143rd pick /2012,13300000.0
33710,2018,was,NsekTy00,Ty Nsekhe,T,79.0,14.0,5.0,3.0,6.0,33.0,10/27/1985,6-8,330.0,texasst,None,2914000.0
33711,2018,was,ParrTi00,Timon Parris,T,61.0,1.0,0.0,0.0,Rook,23.0,9/11/1995,6-6,315.0,Stony Brook,None,129200.0
33712,2018,was,PaynDa00,Daron Payne,NT,95.0,16.0,16.0,8.0,Rook,21.0,5/27/1997,6-3,319.0,alabama,Washington Redskins / 1st / 13th pick /2018,480000.0
33713,2018,was,PeriSa00,Samaje Perine,RB,32.0,5.0,0.0,0.0,1.0,23.0,9/16/1995,5-11,233.0,oklahoma,Washington Redskins / 4th / 114th pick /2017,555000.0
33714,2018,was,PeteAd01,Adrian Peterson,RB,26.0,16.0,16.0,7.0,11.0,33.0,3/21/1985,6-1,220.0,oklahoma,Minnesota Vikings / 1st / 7th pick /2007,1015000.0
33715,2018,was,QuicBr00,Brian Quick,WR,83.0,6.0,3.0,0.0,6.0,29.0,6/5/1989,6-3,215.0,appalachianst,St. Louis Rams / 2nd / 33rd pick /2012,743529.0
33716,2018,was,QuinTr00,Trey Quinn,WR,14.0,3.0,2.0,1.0,Rook,23.0,12/7/1995,6-0,200.0,smu,Washington Redskins / 7th / 256th pick /2018,451760.0
33717,2018,was,ReavJe00,Jeremy Reaves,FS,45.0,2.0,0.0,0.0,Rook,22.0,8/29/1996,5-11,205.0,South Alabama,None,56470.0
33718,2018,was,ReedJo02,Jordan Reed,TE,86.0,13.0,8.0,4.0,5.0,28.0,7/3/1990,6-2,245.0,florida,Washington Redskins / 3rd / 85th pick /2013,8250000.0
33719,2018,was,RichPa01,Paul Richardson,WR,10.0,7.0,4.0,2.0,4.0,26.0,4/13/1992,6-0,170.0,colorado,Seattle Seahawks / 2nd / 45th pick /2014,1500000.0
33720,2018,was,RoulCh00,Chase Roullier,C,73.0,16.0,16.0,6.0,1.0,25.0,8/23/1993,6-4,310.0,wyoming,Washington Redskins / 6th / 199th pick /2017,555000.0
33721,2018,was,SancMa00,Mark Sanchez,QB,6.0,2.0,1.0,0.0,9.0,32.0,11/11/1986,6-2,232.0,usc,New York Jets / 1st / 5th pick /2009,322941.0
33722,2018,was,ScheBr00,Brandon Scherff,RG,75.0,8.0,8.0,3.0,3.0,27.0,12/26/1991,6-5,315.0,iowa,Washington Redskins / 1st / 5th pick /2015,705000.0
33723,2018,was,SettTi00,Tim Settle,NT,97.0,16.0,0.0,1.0,Rook,21.0,7/11/1997,6-3,328.0,virginiatech,Washington Redskins / 5th / 163rd pick /2018,480000.0
33724,2018,was,SimsCa00,Cam Sims,WR,89.0,1.0,0.0,0.0,Rook,22.0,1/6/1996,6-5,214.0,alabama,None,369882.0
33725,2018,was,SmitAl03,Alex Smith,QB,11.0,10.0,10.0,6.0,13.0,34.0,5/7/1984,6-4,213.0,utah,San Francisco 49ers / 1st / 1st pick /2005,13000000.0
33726,2018,was,SmitMa03,Marcus Smith,DE,48.0,2.0,0.0,0.0,4.0,26.0,3/31/1992,6-3,258.0,louisville,Philadelphia Eagles / 1st / 26th pick /2014,790000.0
33727,2018,was,SmitPr00,Preston Smith,LB,94.0,16.0,16.0,8.0,3.0,26.0,11/17/1992,6-5,265.0,mississippist,Washington Redskins / 2nd / 38th pick /2015,1223094.0
33728,2018,was,SpriJe00,Jeremy Sprinkle,TE,87.0,16.0,9.0,0.0,1.0,24.0,8/10/1994,6-5,252.0,arkansas,Washington Redskins / 5th / 154th pick /2017,555000.0
33729,2018,was,StroGr00,Greg Stroman,CB,25.0,15.0,3.0,2.0,Rook,22.0,3/8/1996,5-11,180.0,virginiatech,Washington Redskins / 7th / 241st pick /2018,480000.0
33730,2018,was,SundNi00,Nick Sundberg,C,57.0,13.0,0.0,1.0,8.0,31.0,7/29/1987,6-0,256.0,california,None,915000.0
33731,2018,was,SweaDJ00,D.J. Swearinger,FS,36.0,15.0,15.0,7.0,5.0,27.0,9/1/1991,5-10,205.0,socarolina,Houston Texans / 2nd / 57th pick /2013,3000000.0
33732,2018,was,ThomCh03,Chris Thompson,RB,25.0,10.0,0.0,3.0,5.0,28.0,10/20/1990,5-8,195.0,floridast,Washington Redskins / 5th / 154th pick /2013,1996000.0
33733,2018,was,VigiZa00,Zach Vigil,LB,56.0,14.0,0.0,1.0,3.0,27.0,3/28/1991,6-2,238.0,utahst,None,705000.0
33734,2018,was,WayxTr00,Tress Way,P,5.0,16.0,0.0,2.0,4.0,28.0,4/18/1990,6-1,216.0,oklahoma,None,1350000.0
33735,2018,was,WillTr21,Trent Williams,T,71.0,13.0,13.0,7.0,8.0,30.0,7/19/1988,6-5,320.0,oklahoma,Washington Redskins / 1st / 4th pick /2010,9850000.0

In [3]:
#Check whether tables are inserted or not
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('SELECT name from sqlite_master where type= "table"')
 
    print(cursorObj.fetchall())
sql_fetch(con)

[('game_ids',), ('starters',), ('stats_team',), ('stats_offense',), ('stats_defense',), ('stats_returns',), ('stats_kicking',), ('pass_directions',), ('injury_status',), ('snap_counts',), ('drafts',), ('team_roster',), ('game_info',), ('teams',), ('positions',), ('game_lines',), ('current_injuries',), ('team_game_ids',)]

In [4]:
#Create a Dataframe having year wise details of average humidity,temp,wind chill, wind mph
df_with_YearWise_AvgData = pd.read_sql_query("SELECT season as Year,avg(humidity) as avg_Humidity,avg(temp) as avg_Temp,avg(wind_chill) as avg_Wind_Chill,avg(wind_mph) as avg_Wind_Mph FROM 'game_info' group by season", con)
df_with_YearWise_AvgData

    Year  avg_Humidity   avg_Temp  avg_Wind_Chill  avg_Wind_Mph
0   2002     58.047393  60.955056       23.962547      6.250936
1   2003     59.822115  60.565543       22.101124      6.217228
2   2004     57.918660  59.902622       21.307116      6.636704
3   2005     53.738318  62.082397       25.977528      5.561798
4   2006     54.025000  61.071161       26.479401      5.209738
5   2007     58.472637  61.483146       27.408240      5.602996
6   2008     59.905000  61.157303       31.876404      5.876404
7   2009     59.454545  60.262172       34.453184      4.134831
8   2010     50.281250  59.314607       32.003745      5.187266
9   2011     48.157068  61.734082       30.771536      5.063670
10  2012     57.429319  61.213483       32.996255      4.086142
11  2013     58.561856  61.071161       29.614232      5.157303
12  2014     53.115000  61.172285       34.033708      3.853933
13  2015     56.580000  61.561798       30.535581      4.662921
14  2016     56.744186  61.958801       42.543071      6.003745
15  2017           NaN  61.494382       61.494382      5.786517
16  2018           NaN  61.689139       61.689139      5.475655

In [6]:
#Create a dataframe haviing year wise detail of no. of time home team has won when various criterias are below the average humidity,temp,wind chill and wind mph of that year
df_homeTeam_winsWith_belowAvg_Humidity = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_belowAvg_Humidity FROM 'game_info' where humidity < (select avg(humidity) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_belowAvg_Temp = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_belowAvg_Temp FROM 'game_info' where temp < (select avg(temp) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_belowAvg_WindChill = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_belowAvg_WindChill FROM 'game_info' where wind_chill < (select avg(wind_chill) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_belowAvg_WindMph = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_belowAvg_WindMph FROM 'game_info' where wind_mph < (select avg(wind_mph) from 'game_info') and home = winner group by season", con)

In [7]:
#Create a dataframe haviing year wise detail of no. of time home team has won when various criterias are above the average humidity,temp,wind chill and wind mph of that year
df_homeTeam_winsWith_aboveAvg_Humidity = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_aboveAvg_Humidity FROM 'game_info' where humidity > (select avg(humidity) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_aboveAvg_Temp = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_aboveAvg_Temp FROM 'game_info' where temp > (select avg(temp) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_aboveAvg_WindChill = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_aboveAvg_WindChill FROM 'game_info' where wind_chill > (select avg(wind_chill) from 'game_info') and home = winner group by season", con)
df_homeTeam_winsWith_aboveAvg_WindMph = pd.read_sql_query("SELECT season as Year,count(home) as homeTeam_winsWith_aboveAvg_WindMph FROM 'game_info' where wind_mph > (select avg(wind_mph) from 'game_info') and home = winner group by season", con)

In [8]:
#Create a dataframe haviing year wise detail of no. of time away team has won when various criterias are below the average humidity,temp,wind chill and wind mph of that year
df_awayTeam_winsWith_belowAvg_Humidity = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_belowAvg_Humidity FROM 'game_info' where humidity < (select avg(humidity) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_belowAvg_Temp = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_belowAvg_Temp FROM 'game_info' where temp < (select avg(temp) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_belowAvg_WindChill = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_belowAvg_WindChill FROM 'game_info' where wind_chill < (select avg(wind_chill) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_belowAvg_WindMph = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_belowAvg_WindMph FROM 'game_info' where wind_mph < (select avg(wind_mph) from 'game_info') and away = winner group by season", con)

In [9]:
#Create a dataframe haviing year wise detail of no. of time away team has won when various criterias are above the average humidity,temp,wind chill and wind mph of that year
df_awayTeam_winsWith_aboveAvg_Humidity = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_aboveAvg_Humidity FROM 'game_info' where humidity > (select avg(humidity) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_aboveAvg_Temp = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_aboveAvg_Temp FROM 'game_info' where temp > (select avg(temp) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_aboveAvg_WindChill = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_aboveAvg_WindChill FROM 'game_info' where wind_chill > (select avg(wind_chill) from 'game_info') and away = winner group by season", con)
df_awayTeam_winsWith_aboveAvg_WindMph = pd.read_sql_query("SELECT season as Year,count(away) as awayTeam_winsWith_aboveAvg_WindMph FROM 'game_info' where wind_mph > (select avg(wind_mph) from 'game_info') and away = winner group by season", con)

In [10]:
#Merging the average value dataframe with the count of home and away winners wih respect to below or above average humidity,temp etc.
df_forBar_Chart = pd.concat([df_with_YearWise_AvgData, df_homeTeam_winsWith_belowAvg_Humidity["homeTeam_winsWith_belowAvg_Humidity"], df_homeTeam_winsWith_belowAvg_Temp["homeTeam_winsWith_belowAvg_Temp"], df_homeTeam_winsWith_belowAvg_WindChill["homeTeam_winsWith_belowAvg_WindChill"], df_homeTeam_winsWith_belowAvg_WindMph["homeTeam_winsWith_belowAvg_WindMph"], df_homeTeam_winsWith_aboveAvg_Humidity["homeTeam_winsWith_aboveAvg_Humidity"], df_homeTeam_winsWith_aboveAvg_Temp["homeTeam_winsWith_aboveAvg_Temp"], df_homeTeam_winsWith_aboveAvg_WindChill["homeTeam_winsWith_aboveAvg_WindChill"], df_homeTeam_winsWith_aboveAvg_WindMph["homeTeam_winsWith_aboveAvg_WindMph"], df_awayTeam_winsWith_belowAvg_Humidity["awayTeam_winsWith_belowAvg_Humidity"], df_awayTeam_winsWith_belowAvg_Temp["awayTeam_winsWith_belowAvg_Temp"], df_awayTeam_winsWith_belowAvg_WindChill["awayTeam_winsWith_belowAvg_WindChill"], df_awayTeam_winsWith_belowAvg_WindMph["awayTeam_winsWith_belowAvg_WindMph"], df_awayTeam_winsWith_aboveAvg_Humidity["awayTeam_winsWith_aboveAvg_Humidity"], df_awayTeam_winsWith_aboveAvg_Temp["awayTeam_winsWith_aboveAvg_Temp"], df_awayTeam_winsWith_aboveAvg_WindChill["awayTeam_winsWith_aboveAvg_WindChill"], df_awayTeam_winsWith_aboveAvg_WindMph["awayTeam_winsWith_aboveAvg_WindMph"]], axis=1)
df_forBar_Chart.fillna(0, inplace=True)
pd.options.display.float_format = '{:,.0f}'.format
df_forBar_Chart.set_index('Year')
df_forBar_Chart[['Year','avg_Humidity','avg_Temp','avg_Wind_Chill','avg_Wind_Mph','homeTeam_winsWith_belowAvg_Humidity','homeTeam_winsWith_belowAvg_Temp','homeTeam_winsWith_belowAvg_WindChill','homeTeam_winsWith_belowAvg_WindMph','homeTeam_winsWith_aboveAvg_Humidity','homeTeam_winsWith_aboveAvg_Temp','homeTeam_winsWith_aboveAvg_WindChill','homeTeam_winsWith_aboveAvg_WindMph']]
df_forBar_Chart

,Year,avg_Humidity,avg_Temp,avg_Wind_Chill,avg_Wind_Mph,homeTeam_winsWith_belowAvg_Humidity,homeTeam_winsWith_belowAvg_Temp,homeTeam_winsWith_belowAvg_WindChill,homeTeam_winsWith_belowAvg_WindMph,homeTeam_winsWith_aboveAvg_Humidity,...,homeTeam_winsWith_aboveAvg_WindChill,homeTeam_winsWith_aboveAvg_WindMph,awayTeam_winsWith_belowAvg_Humidity,awayTeam_winsWith_belowAvg_Temp,awayTeam_winsWith_belowAvg_WindChill,awayTeam_winsWith_belowAvg_WindMph,awayTeam_winsWith_aboveAvg_Humidity,awayTeam_winsWith_aboveAvg_Temp,awayTeam_winsWith_aboveAvg_WindChill,awayTeam_winsWith_aboveAvg_WindMph
0,2002,58,61,24,6,49,74,106,73,78,...,50,83,35,41,70,51,48,69,40,59
1,2003,60,61,22,6,48,73,114,73,80,...,49,90,35,42,70,47,45,62,34,57
2,2004,58,60,21,7,52,69,103,80,64,...,49,72,42,56,81,49,51,59,34,66
3,2005,54,62,26,6,67,72,105,82,62,...,51,74,45,43,63,62,40,68,48,49
4,2006,54,61,26,5,62,63,94,76,48,...,50,68,45,53,67,74,45,70,56,49
5,2007,58,61,27,6,49,63,90,81,68,...,62,71,41,40,71,60,43,75,44,55
6,2008,60,61,32,6,55,52,78,90,57,...,73,61,32,48,65,62,55,67,50,53
7,2009,59,60,34,4,49,61,70,98,54,...,83,55,40,53,59,72,44,61,55,42
8,2010,50,59,32,5,57,65,74,90,49,...,74,58,46,47,67,65,40,72,52,54
9,2011,48,62,31,5,62,61,82,90,49,...,71,63,49,44,62,68,31,70,52,46
10,2012,57,61,33,4,54,58,73,103,51,...,80,50,41,51,58,75,44,62,55,38
11,2013,59,61,30,5,52,61,90,88,64,...,69,71,40,36,58,61,37,71,49,46
12,2014,53,61,34,4,58,67,79,100,54,...,75,54,45,45,46,80,42,67,66,32
13,2015,57,62,31,5,51,65,76,89,58,...,68,55,39,45,63,76,52,78,60,47
14,2016,57,62,43,6,20,56,51,77,26,...,104,78,21,41,38,56,18,69,72,54
15,2017,0,61,61,6,0,56,14,86,0,...,138,66,0,41,10,53,0,74,105,62
16,2018,0,62,62,5,0,65,10,89,0,...,149,70,0,49,5,56,0,57,101,50

In [11]:
# Adding lart row in the dataframe with aggregate values an saving the dataframe to sqlite db
import numpy as np
total = df_forBar_Chart.apply(np.sum)
total['Year'] = 'Aggregate'
total['avg_Humidity'] = total['avg_Humidity'] / 17
total['avg_Temp'] = total['avg_Temp'] / 17
total['avg_Wind_Chill'] = total['avg_Wind_Chill'] / 17
total['avg_Wind_Mph'] = total['avg_Wind_Mph'] / 17
total = pd.DataFrame(total.values, index=total.keys()).T
df_forBar_Chart = total.append(df_forBar_Chart, ignore_index=True)
df_forBar_Chart
df_forBar_Chart.to_sql("dataForBarGraph", con, if_exists="replace")